all: clean entab detab tl srt dcls

entab:
	gcc -g ex12.c -o entab

detab:
	gcc -g ex12.c -o detab

tl:
	gcc -g ex13.c -o tl

srt:
	gcc -g srt.c -o srt

dcls:
	gcc -g -Wall -Wextra dcls.c -o dcls

clean:
	rm -f entab detab tl srt dcls
